default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: bookstore-tutorial-backend_development
  username: postgres
  password: our-awesome-bookstore-app
  host: localhost

test:
  <<: *development
  database: bookstore-tutorial-backend_test

production:
  <<: *default
  database: bookstore-tutorial-backend_production
  username: bookstore-tutorial-backend
  password: <%= ENV['BOOKSTORE-TUTORIAL-BACKEND_DATABASE_PASSWORD'] %>
